export const masterList = {
    "0": {
        "id": 2035,
        "box": 1131,
        "answer": 78,
        "name_hu": "Galata torony",
        "country_hu": "Törökország",
        "city_hu": "Isztambul",
        "name_en": "Galata tower",
        "country_en": "Turkey",
        "city_en": "Istanbul"
    },
    "1": {
        "id": 2085,
        "box": 1724,
        "answer": 76,
        "name_hu": "Kanadai Nemzeti TV-Torony",
        "country_hu": "Kanada",
        "city_hu": "Toronto",
        "name_en": "Canadian National tower",
        "country_en": "Canada",
        "city_en": "Toronto"
    },
    "2": {
        "id": 2154,
        "box": 1542,
        "answer": 18,
        "name_hu": "Santa Maria 1492",
        "country_hu": "Spanyolország",
        "city_hu": "[elsüllyedt]",
        "name_en": "Santa Maria 1492",
        "country_en": "Spain",
        "city_en": "[sank]"
    },
    "3": {
        "id": 2194,
        "box": 1050,
        "answer": 27,
        "name_hu": "Szent Vitus-székesegyház",
        "country_hu": "Csehország",
        "city_hu": "Prága",
        "name_en": "St. Vitus cathedral",
        "country_en": "Czech Republic",
        "city_en": "Prague"
    },
    "4": {
        "id": 2340,
        "box": 1012,
        "answer": 48,
        "name_hu": "Mustafa Kemal Atatürk mauzóleuma",
        "country_hu": "Törökország",
        "city_hu": "Ankara",
        "name_en": "Mausoleum Of Mustafa Kemal Atatürk",
        "country_en": "Turkey",
        "city_en": "Ankara"
    },
    "5": {
        "id": 2354,
        "box": 1570,
        "answer": 22,
        "name_hu": "New York-i Szabadság szobor",
        "country_hu": "Egyesült Államok",
        "city_hu": "New York",
        "name_en": "Statue of Liberty",
        "country_en": "United States of America",
        "city_en": "New York"
    },
    "6": {
        "id": 2366,
        "box": 1806,
        "answer": 69,
        "name_hu": "Pisai ferde torony",
        "country_hu": "Olaszország",
        "city_hu": "Pisa",
        "name_en": "Leaning tower of Pisa",
        "country_en": "Italy",
        "city_en": "Pisa"
    },
    "7": {
        "id": 2501,
        "box": 1760,
        "answer": 12,
        "name_hu": "Holland szélmalom",
        "country_hu": "Hollandia",
        "city_hu": "Kinderdijk",
        "name_en": "Dutch windmill",
        "country_en": "Netherlands",
        "city_en": "Kinderdijk"
    },
    "8": {
        "id": 2615,
        "box": 1087,
        "answer": 13,
        "name_hu": "Országház",
        "country_hu": "Magyarország",
        "city_hu": "Budapest",
        "name_en": "Hungarian Parliament",
        "country_en": "Hungary",
        "city_en": "Budapest"
    },
    "9": {
        "id": 2676,
        "box": 1282,
        "answer": 61,
        "name_hu": "Anna királynő bosszúja",
        "country_hu": "Egyesült Királyság",
        "city_hu": "[elsüllyedt]",
        "name_en": "Queen Anne's Revenge",
        "country_en": "United Kingdom",
        "city_en": "[sank]"
    },
    "10": {
        "id": 2695,
        "box": 1425,
        "answer": 68,
        "name_hu": "Ahmed Szultán Mecset",
        "country_hu": "Törökország",
        "city_hu": "Isztambul",
        "name_en": "Sultan Ahmed Mosque",
        "country_en": "Turkey",
        "city_en": "Istanbul"
    },
    "11": {
        "id": 2720,
        "box": 1671,
        "answer": 60,
        "name_hu": "Boldog Vazul-székesegyház",
        "country_hu": "Oroszország",
        "city_hu": "Moszkva",
        "name_en": "Saint Basil's cathedral",
        "country_en": "Russia",
        "city_en": "Moscow"
    },
    "12": {
        "id": 2762,
        "box": 1651,
        "answer": 32,
        "name_hu": "Sky Tower",
        "country_hu": "Új-Zéland",
        "city_hu": "Auckland",
        "name_en": "Sky tower",
        "country_en": "New-Zealand",
        "city_en": "Auckland"
    },
    "13": {
        "id": 2795,
        "box": 1583,
        "answer": 34,
        "name_hu": "Szent Patrik-katedrális",
        "country_hu": "Egyesült Államok",
        "city_hu": "New York",
        "name_en": "St. Patrick cathedral",
        "country_en": "United States of America",
        "city_en": "New York"
    },
    "14": {
        "id": 2987,
        "box": 1915,
        "answer": 89,
        "name_hu": "Oszaka várkastély",
        "country_hu": "Japán",
        "city_hu": "Oszaka",
        "name_en": "Osaka castle Hall",
        "country_en": "Japan",
        "city_en": "Osaka"
    },
    "15": {
        "id": 3074,
        "box": 1668,
        "answer": 98,
        "name_hu": "Szent Márk tér",
        "country_hu": "Olaszország",
        "city_hu": "Velence",
        "name_en": "St. Mark square",
        "country_en": "Italy",
        "city_en": "Venice"
    },
    "16": {
        "id": 3095,
        "box": 1346,
        "answer": 36,
        "name_hu": "Brooklyn-híd",
        "country_hu": "Egyesült Államok",
        "city_hu": "New York",
        "name_en": "Brooklyn bridge",
        "country_en": "United States of America",
        "city_en": "New York"
    },
    "17": {
        "id": 3265,
        "box": 1413,
        "answer": 91,
        "name_hu": "Kölni dóm",
        "country_hu": "Németország",
        "city_hu": "Köln",
        "name_en": "Cologne cathedral",
        "country_en": "Germany",
        "city_en": "Cologne"
    },
    "18": {
        "id": 3278,
        "box": 1310,
        "answer": 63,
        "name_hu": "Mayflower",
        "country_hu": "Hollandia",
        "city_hu": "[elsüllyedt]",
        "name_en": "Mayflower",
        "country_en": "Netherlands",
        "city_en": "[sank]"
    },
    "19": {
        "id": 3316,
        "box": 1928,
        "answer": 6,
        "name_hu": "Al-Masjid al-Haram",
        "country_hu": "Szaúd-Arábia",
        "city_hu": "Mekka",
        "name_en": "Al-Masjid al-Haram",
        "country_en": "Saudi Arabia",
        "city_en": "Mekka"
    },
    "20": {
        "id": 3423,
        "box": 1131,
        "answer": 57,
        "name_hu": "Wat Phra Kaew",
        "country_hu": "Thaiföld",
        "city_hu": "Bangkok",
        "name_en": "Wat Phra Kaew",
        "country_en": "Thailand",
        "city_en": "Bangkok"
    },
    "21": {
        "id": 3489,
        "box": 1087,
        "answer": 43,
        "name_hu": "Szent Pál-székesegyház",
        "country_hu": "Egyesült Királyság",
        "city_hu": "London",
        "name_en": "St. Paul cathedral",
        "country_en": "United Kingdom",
        "city_en": "London"
    },
    "22": {
        "id": 3609,
        "box": 1642,
        "answer": 2,
        "name_hu": "Tower-híd",
        "country_hu": "Egyesült Királyság",
        "city_hu": "London",
        "name_en": "Tower bridge",
        "country_en": "United Kingdom",
        "city_en": "London"
    },
    "23": {
        "id": 3735,
        "box": 0,
        "answer": 42,
        "name_hu": "Burj Al Arab",
        "country_hu": "Egyesült Arab Emírségek",
        "city_hu": "Dubai",
        "name_en": "Burj Al Arab",
        "country_en": "United Arab Emirates",
        "city_en": "Dubai"
    },
    "24": {
        "id": 3848,
        "box": 1131,
        "answer": 87,
        "name_hu": "Waweli Székesegyház",
        "country_hu": "Lengyelország",
        "city_hu": "Krakkó",
        "name_en": "Wawel cathedral",
        "country_en": "Poland",
        "city_en": "Kraków"
    },
    "25": {
        "id": 3975,
        "box": 1420,
        "answer": 55,
        "name_hu": "Akhmad Kadyrov mecset",
        "country_hu": "Oroszország",
        "city_hu": "Grozníj",
        "name_en": "Akhmad Kadyrov mosque",
        "country_en": "Russia",
        "city_en": "Grozny"
    },
    "26": {
        "id": 4025,
        "box": 1087,
        "answer": 82,
        "name_hu": "Willis-torony",
        "country_hu": "Egyesült Államok",
        "city_hu": "Chicago",
        "name_en": "Willis tower",
        "country_en": "United States of America",
        "city_en": "Chicago"
    },
    "27": {
        "id": 4190,
        "box": 1240,
        "answer": 41,
        "name_hu": "Neuschwanstein kastély",
        "country_hu": "Németország",
        "city_hu": "Schwangau",
        "name_en": "Neuschwanstein castle",
        "country_en": "Germany",
        "city_en": "Schwangau"
    },
    "28": {
        "id": 4240,
        "box": 1724,
        "answer": 92,
        "name_hu": "Tokyo Skytree",
        "country_hu": "Japán",
        "city_hu": "Tokió",
        "name_en": "Tokyo Skytree",
        "country_en": "Japan",
        "city_en": "Tokyo"
    },
    "29": {
        "id": 4342,
        "box": 1432,
        "answer": 9,
        "name_hu": "Chrysler Building",
        "country_hu": "Egyesült Államok",
        "city_hu": "New York",
        "name_en": "Chrysler Building",
        "country_en": "United States of America",
        "city_en": "New York"
    },
    "30": {
        "id": 4355,
        "box": 0,
        "answer": 37,
        "name_hu": "Burj Kalifa",
        "country_hu": "Egyesült Arab Emírségek",
        "city_hu": "Dubai",
        "name_en": "Burj Kalifa",
        "country_en": "United Arab Emirates",
        "city_en": "Dubai"
    },
    "31": {
        "id": 4367,
        "box": 1766,
        "answer": 51,
        "name_hu": "Suzhou-i klasszikus kert",
        "country_hu": "Kína",
        "city_hu": "Suzhou",
        "name_en": "Suzhou classic garden",
        "country_en": "China",
        "city_en": "Suzhou"
    },
    "32": {
        "id": 4485,
        "box": 1883,
        "answer": 40,
        "name_hu": "Szent Izsák-székesegyház",
        "country_hu": "Oroszország",
        "city_hu": "Szentpétervár",
        "name_en": "St. Isaac's cathedral",
        "country_en": "Russia",
        "city_en": "Saint Petersburg"
    },
    "33": {
        "id": 4512,
        "box": 1481,
        "answer": 85,
        "name_hu": "Hluboká kastély",
        "country_hu": "Csehország",
        "city_hu": "Hluboká nad Vltavou",
        "name_en": "Hluboká castle",
        "country_en": "Czech Republic",
        "city_en": "Hluboká nad Vltavou"
    },
    "34": {
        "id": 4638,
        "box": 1111,
        "answer": 77,
        "name_hu": "Prágai csillagászati óra és a városháza",
        "country_hu": "Csehország",
        "city_hu": "Prága",
        "name_en": "Prague Astronomical Clock and Town Hall",
        "country_en": "Czech Republic",
        "city_en": "Prague"
    },
    "35": {
        "id": 4677,
        "box": 1131,
        "answer": 73,
        "name_hu": "Pekingi Siheyuan",
        "country_hu": "Kína",
        "city_hu": "Peking",
        "name_en": "Beijing Siheyuan",
        "country_en": "China",
        "city_en": "Beijing"
    },
    "36": {
        "id": 4721,
        "box": 1768,
        "answer": 4,
        "name_hu": "Keleti Gyöngy torony",
        "country_hu": "Kína",
        "city_hu": "Shanghai",
        "name_en": "Oriental pearl",
        "country_en": "China",
        "city_en": "Shanghai"
    },
    "37": {
        "id": 4794,
        "box": 0,
        "answer": 97,
        "name_hu": "Eiffel Torony",
        "country_hu": "Franciaország",
        "city_hu": "Párizs",
        "name_en": "Eiffel tower",
        "country_en": "France",
        "city_en": "Paris"
    },
    "38": {
        "id": 4805,
        "box": 1806,
        "answer": 59,
        "name_hu": "Megváltó Krisztus szobra",
        "country_hu": "Brazília",
        "city_hu": "Rio de Janeiro",
        "name_en": "Christ redeemer",
        "country_en": "Brasil",
        "city_en": "Rio de Janeiro"
    },
    "39": {
        "id": 4837,
        "box": 0,
        "answer": 19,
        "name_hu": "Eyüp Sultan mecset",
        "country_hu": "Törökország",
        "city_hu": "Isztambul",
        "name_en": "Eyüp Sultan mosque",
        "country_en": "Turkey",
        "city_en": "Istanbul"
    },
    "40": {
        "id": 4954,
        "box": 1806,
        "answer": 52,
        "name_hu": "Mississippi gőzhajó",
        "country_hu": "Egyesült Államok",
        "city_hu": "New Orleans",
        "name_en": "Mississippi steamship",
        "country_en": "United States of America",
        "city_en": "New Orleans"
    },
    "41": {
        "id": 4982,
        "box": 0,
        "answer": 71,
        "name_hu": "Tokiói Torony",
        "country_hu": "Japán",
        "city_hu": "Tokió",
        "name_en": "Tokyo Tower",
        "country_en": "Japan",
        "city_en": "Tokyo"
    },
    "42": {
        "id": 5047,
        "box": 1346,
        "answer": 7,
        "name_hu": "Széchenyi Lánchíd",
        "country_hu": "Magyarország",
        "city_hu": "Budapest",
        "name_en": "Szechenyi Chain bridge",
        "country_en": "Hungary",
        "city_en": "Budapest"
    },
    "43": {
        "id": 5131,
        "box": 1915,
        "answer": 1,
        "name_hu": "Kaminarimon Kapu",
        "country_hu": "Japán",
        "city_hu": "Tokió",
        "name_en": "Kaminarimon Gate",
        "country_en": "Japan",
        "city_en": "Tokyo"
    },
    "44": {
        "id": 5210,
        "box": 1570,
        "answer": 15,
        "name_hu": "Kínai Nagy Fal",
        "country_hu": "Kína",
        "city_hu": "-",
        "name_en": "Great wall of China",
        "country_en": "China",
        "city_en": "-"
    },
    "45": {
        "id": 5408,
        "box": 1998,
        "answer": 83,
        "name_hu": "Peles kastély",
        "country_hu": "Románia",
        "city_hu": "Szinaja",
        "name_en": "Peles castle",
        "country_en": "Romania",
        "city_en": "Sinaia"
    },
    "46": {
        "id": 5466,
        "box": 1724,
        "answer": 80,
        "name_hu": "Kultúra és Tudomány Palotája",
        "country_hu": "Lengyelország",
        "city_hu": "Varsó",
        "name_en": "Palace of culture and science",
        "country_en": "Poland",
        "city_en": "Warsaw"
    },
    "47": {
        "id": 5517,
        "box": 1472,
        "answer": 44,
        "name_hu": "Bolygó Hollandi szellemhajó",
        "country_hu": "Hollandia",
        "city_hu": "-",
        "name_en": "Flying Dutchman ghostship",
        "country_en": "Netherlands",
        "city_en": "-"
    },
    "48": {
        "id": 5519,
        "box": 1012,
        "answer": 5,
        "name_hu": "Varsói Királyi palota",
        "country_hu": "Lengyelország",
        "city_hu": "Varsó",
        "name_en": "The Royal castle in Warsaw",
        "country_en": "Poland",
        "city_en": "Warsaw"
    },
    "49": {
        "id": 5588,
        "box": 1458,
        "answer": 75,
        "name_hu": "Al-Masjid an-Nabawi",
        "country_hu": "Szaúd-Arábia",
        "city_hu": "Medina",
        "name_en": "Al-Masjid an-Nabawi",
        "country_en": "Saudi Arabia",
        "city_en": "Medina"
    },
    "50": {
        "id": 5641,
        "box": 1012,
        "answer": 31,
        "name_hu": "Himedzsi várkastély",
        "country_hu": "Japán",
        "city_hu": "Himedzsi",
        "name_en": "Himeji castle",
        "country_en": "Japan",
        "city_en": "Himeji"
    },
    "51": {
        "id": 6036,
        "box": 1651,
        "answer": 8,
        "name_hu": "Bank of China Tower",
        "country_hu": "Kína",
        "city_hu": "Hong Kong",
        "name_en": "Bank of China tower",
        "country_en": "China",
        "city_en": "Hong Kong"
    },
    "52": {
        "id": 6114,
        "box": 1382,
        "answer": 64,
        "name_hu": "Uszpenszkíj-székesegyház",
        "country_hu": "Oroszország",
        "city_hu": "Moszkva",
        "name_en": "Uspenski cathedral",
        "country_en": "Russia",
        "city_en": "Moscow"
    },
    "53": {
        "id": 6118,
        "box": 1262,
        "answer": 10,
        "name_hu": "Brandenburgi kapu",
        "country_hu": "Németország",
        "city_hu": "Berlin",
        "name_en": "Brandenburg gate",
        "country_en": "Germany",
        "city_en": "Berlin"
    },
    "54": {
        "id": 6144,
        "box": 1362,
        "answer": 96,
        "name_hu": "Szent István-bazilika",
        "country_hu": "Magyarország",
        "city_hu": "Budapest",
        "name_en": "St. Stephen's basilica",
        "country_en": "Hungary",
        "city_en": "Budapest"
    },
    "55": {
        "id": 6192,
        "box": 1374,
        "answer": 94,
        "name_hu": "Hagia Sophia",
        "country_hu": "Törökország",
        "city_hu": "Isztambul",
        "name_en": "Hagia Sophia",
        "country_en": "Turkey",
        "city_en": "Istanbul"
    },
    "56": {
        "id": 6316,
        "box": 1806,
        "answer": 53,
        "name_hu": "Tadzs Mahal",
        "country_hu": "India",
        "city_hu": "Agra",
        "name_en": "Taj Mahal",
        "country_en": "India",
        "city_en": "Agra"
    },
    "57": {
        "id": 6381,
        "box": 1220,
        "answer": 38,
        "name_hu": "A moszkvai Kreml Fala",
        "country_hu": "Oroszország",
        "city_hu": "Moszkva",
        "name_en": "The Moscow Kremlin Wall",
        "country_en": "Russia",
        "city_en": "Moscow"
    },
    "58": {
        "id": 6389,
        "box": 1352,
        "answer": 65,
        "name_hu": "Vajdahunyad vára",
        "country_hu": "Magyarország",
        "city_hu": "Budapest",
        "name_en": "Vajdahunyad castle",
        "country_en": "Hungary",
        "city_en": "Budapest"
    },
    "59": {
        "id": 6509,
        "box": 1806,
        "answer": 46,
        "name_hu": "Az ég temploma",
        "country_hu": "Kína",
        "city_hu": "Peking",
        "name_en": "Temple of Heaven",
        "country_en": "China",
        "city_en": "Beijing"
    },
    "60": {
        "id": 6522,
        "box": 1806,
        "answer": 81,
        "name_hu": "Sydney-i Operaház",
        "country_hu": "Ausztrália",
        "city_hu": "Sydney",
        "name_en": "Sydney opera house",
        "country_en": "Australia",
        "city_en": "Sydney"
    },
    "61": {
        "id": 6558,
        "box": 1710,
        "answer": 50,
        "name_hu": "Szmolníj székesegyház",
        "country_hu": "Oroszország",
        "city_hu": "Szentpétervár",
        "name_en": "Smolny cathedral",
        "country_en": "Russia",
        "city_en": "Saint Petersburg"
    },
    "62": {
        "id": 6644,
        "box": 1881,
        "answer": 56,
        "name_hu": "Szent Péter-bazilika",
        "country_hu": "Vatikán",
        "city_hu": "Vatikán Város",
        "name_en": "St. Peter's basilica",
        "country_en": "Vatican",
        "city_en": "Vatican City"
    },
    "63": {
        "id": 6653,
        "box": 1966,
        "answer": 58,
        "name_hu": "Esztergomi Bazilika",
        "country_hu": "Magyarország",
        "city_hu": "Esztergom",
        "name_en": "Esztergom Basilica",
        "country_en": "Hungary",
        "city_en": "Esztergom"
    },
    "64": {
        "id": 6795,
        "box": 1642,
        "answer": 14,
        "name_hu": "Szent Jakab-katedrális",
        "country_hu": "Spanyolország",
        "city_hu": "Santiago d. C.",
        "name_en": "St. Jacob's cathedral",
        "country_en": "Spain",
        "city_en": "Santiago d. C."
    },
    "65": {
        "id": 6841,
        "box": 1910,
        "answer": 3,
        "name_hu": "Hohenzollern kastély",
        "country_hu": "Németország",
        "city_hu": "Bisingen",
        "name_en": "Hohenzollern castle",
        "country_en": "Germany",
        "city_en": "Bisingen"
    },
    "66": {
        "id": 6939,
        "box": 1131,
        "answer": 33,
        "name_hu": "Lincoln emlékmű",
        "country_hu": "Egyesült Államok",
        "city_hu": "Washington",
        "name_en": "Lincoln memorial",
        "country_en": "United States of America",
        "city_en": "Washington"
    },
    "67": {
        "id": 7148,
        "box": 1131,
        "answer": 95,
        "name_hu": "Taipei 101 Building",
        "country_hu": "Tajvan",
        "city_hu": "Taipei",
        "name_en": "Taipei 101 Building",
        "country_en": "Taiwan",
        "city_en": "Taipei"
    },
    "68": {
        "id": 7310,
        "box": 1724,
        "answer": 74,
        "name_hu": "Notre-Dame",
        "country_hu": "Franciaország",
        "city_hu": "Párizs",
        "name_en": "Notre-Dame",
        "country_en": "France",
        "city_en": "Paris"
    },
    "69": {
        "id": 7401,
        "box": 1724,
        "answer": 84,
        "name_hu": "Petronas-ikertorony",
        "country_hu": "Malajzia",
        "city_hu": "Kuala Lumpur",
        "name_en": "Petronas twin-tower",
        "country_en": "Malaysia",
        "city_en": "Kuala Lumpur"
    },
    "70": {
        "id": 7582,
        "box": 1825,
        "answer": 67,
        "name_hu": "Esmeralda 1855",
        "country_hu": "Chile",
        "city_hu": "[elsüllyedt]",
        "name_en": "Esmeralda 1855",
        "country_en": "Chile",
        "city_en": "[sank]"
    },
    "71": {
        "id": 7619,
        "box": 1293,
        "answer": 23,
        "name_hu": "Firenzei Dóm",
        "country_hu": "Olaszország",
        "city_hu": "Firenze",
        "name_en": "Cattedrale Santa Maria del Fiore",
        "country_en": "Italy",
        "city_en": "Firenze"
    },
    "72": {
        "id": 7805,
        "box": 1991,
        "answer": 62,
        "name_hu": "A Vérző Megváltó temploma",
        "country_hu": "Oroszország",
        "city_hu": "Szentpétervár",
        "name_en": "The Church of the Saviour on the Blood",
        "country_en": "Russia",
        "city_en": "Saint Petersburg"
    },
    "73": {
        "id": 8032,
        "box": 1262,
        "answer": 35,
        "name_hu": "Buckingham Palota",
        "country_hu": "Egyesült Királyság",
        "city_hu": "London",
        "name_en": "Buckingham Palace",
        "country_en": "United Kingdom",
        "city_en": "London"
    },
    "74": {
        "id": 8052,
        "box": 1724,
        "answer": 79,
        "name_hu": "Colosseum",
        "country_hu": "Olaszország",
        "city_hu": "Róma",
        "name_en": "Colosseum",
        "country_en": "Italy",
        "city_en": "Rome"
    },
    "75": {
        "id": 8053,
        "box": 1651,
        "answer": 26,
        "name_hu": "Milánói Dóm",
        "country_hu": "Olaszország",
        "city_hu": "Milánó",
        "name_en": "Milan Cathedral",
        "country_en": "Italy",
        "city_en": "Milan"
    },
    "76": {
        "id": 8171,
        "box": 1080,
        "answer": 29,
        "name_hu": "San Felipe 1690",
        "country_hu": "Spanyolország",
        "city_hu": "[elsüllyedt]",
        "name_en": "San Felipe 1690",
        "country_en": "Spain",
        "city_en": "[sank]"
    },
    "77": {
        "id": 8261,
        "box": 0,
        "answer": 11,
        "name_hu": "Titanic",
        "country_hu": "Egyesült Királyság",
        "city_hu": "[elsüllyedt]",
        "name_en": "Titanic",
        "country_en": "United Kingdom",
        "city_en": "[sank]"
    },
    "78": {
        "id": 8422,
        "box": 1111,
        "answer": 49,
        "name_hu": "Hat hölgy kastély",
        "country_hu": "Franciaország",
        "city_hu": "Chenonceaux",
        "name_en": "Château de Chenonceau",
        "country_en": "France",
        "city_en": "Chenonceaux"
    },
    "79": {
        "id": 8447,
        "box": 1620,
        "answer": 99,
        "name_hu": "HMS Victory 1765",
        "country_hu": "Egyesült Királyság",
        "city_hu": "Boston",
        "name_en": "HMS Victory 1765",
        "country_en": "United Kingdom",
        "city_en": "Boston"
    },
    "80": {
        "id": 8465,
        "box": 0,
        "answer": 39,
        "name_hu": "Fehér Ház",
        "country_hu": "Egyesült Államok",
        "city_hu": "Washington",
        "name_en": "White house",
        "country_en": "United States of America",
        "city_en": "Washington"
    },
    "81": {
        "id": 8550,
        "box": 1012,
        "answer": 54,
        "name_hu": "Harry Potter Roxfort Kastély",
        "country_hu": "Egyesült Királyság",
        "city_hu": "Alnwick",
        "name_en": "Harry Potter Hogwarts castle",
        "country_en": "United Kingdom",
        "city_en": "Alnwick"
    },
    "82": {
        "id": 8790,
        "box": 1515,
        "answer": 88,
        "name_hu": "Római csatahajó",
        "country_hu": "Olaszország",
        "city_hu": "[elsüllyedt]",
        "name_en": "Roman warship",
        "country_en": "Italy",
        "city_en": "[sank]"
    },
    "83": {
        "id": 8922,
        "box": 1034,
        "answer": 24,
        "name_hu": "HMS Beagle",
        "country_hu": "Egyesült Királyság",
        "city_hu": "[elsüllyedt]",
        "name_en": "HMS Beagle",
        "country_en": "United Kingdom",
        "city_en": "[sank]"
    },
    "84": {
        "id": 8948,
        "box": 1632,
        "answer": 30,
        "name_hu": "Mátyás-templom és Halászbástya",
        "country_hu": "Magyarország",
        "city_hu": "Budapest",
        "name_en": "Matthias church & Fisherman's bastione",
        "country_en": "Hungary",
        "city_en": "Budapest"
    },
    "85": {
        "id": 9010,
        "box": 1352,
        "answer": 25,
        "name_hu": "Kul Sharif mecset",
        "country_hu": "Oroszország",
        "city_hu": "Kazán",
        "name_en": "Kul Sharif mosque",
        "country_en": "Russia",
        "city_en": "Kazan"
    },
    "86": {
        "id": 9040,
        "box": 1220,
        "answer": 70,
        "name_hu": "Sagrada Família",
        "country_hu": "Spanyolország",
        "city_hu": "Barcelona",
        "name_en": "Sagrada Familia",
        "country_en": "Spain",
        "city_en": "Barcelona"
    },
    "87": {
        "id": 9118,
        "box": 1131,
        "answer": 100,
        "name_hu": "Diadalív",
        "country_hu": "Franciaország",
        "city_hu": "Párizs",
        "name_en": "Triumphal Arch",
        "country_en": "France",
        "city_en": "Paris"
    },
    "88": {
        "id": 9213,
        "box": 1542,
        "answer": 47,
        "name_hu": "USS Constitution 1797",
        "country_hu": "Egyesült Államok",
        "city_hu": "Boston",
        "name_en": "USS Constitution 1797",
        "country_en": "United States of America",
        "city_en": "Boston"
    },
    "89": {
        "id": 9218,
        "box": 1534,
        "answer": 66,
        "name_hu": "Megváltó Krisztus-székesegyház",
        "country_hu": "Oroszország",
        "city_hu": "Moszkva",
        "name_en": "Cathedral of Christ the Saviour",
        "country_en": "Russia",
        "city_en": "Moscow"
    },
    "90": {
        "id": 9266,
        "box": 1651,
        "answer": 93,
        "name_hu": "Louvre Múzeum",
        "country_hu": "Franciaország",
        "city_hu": "Párizs",
        "name_en": "Louvre",
        "country_en": "France",
        "city_en": "Paris"
    },
    "91": {
        "id": 9461,
        "box": 1724,
        "answer": 72,
        "name_hu": "Groupama Aréna",
        "country_hu": "Magyarország",
        "city_hu": "Budapest",
        "name_en": "Groupama arena",
        "country_en": "Hungary",
        "city_en": "Budapest"
    },
    "92": {
        "id": 9483,
        "box": 1131,
        "answer": 20,
        "name_hu": "Mennyei béke kapuja",
        "country_hu": "Kína",
        "city_hu": "Peking",
        "name_en": "Tiananmen",
        "country_en": "China",
        "city_en": "Beijing"
    },
    "93": {
        "id": 9596,
        "box": 1844,
        "answer": 86,
        "name_hu": "Westminsteri Apátság",
        "country_hu": "Egyesült Királyság",
        "city_hu": "London",
        "name_en": "Westminster Abbey",
        "country_en": "United Kingdom",
        "city_en": "London"
    },
    "94": {
        "id": 9658,
        "box": 1971,
        "answer": 17,
        "name_hu": "Törcsvári kastély",
        "country_hu": "Románia",
        "city_hu": "Törcsvár",
        "name_en": "Bran castle",
        "country_en": "Romania",
        "city_en": "Bran"
    },
    "95": {
        "id": 9675,
        "box": 1425,
        "answer": 90,
        "name_hu": "Hősök tere",
        "country_hu": "Magyarország",
        "city_hu": "Budapest",
        "name_en": "Heroes' Square",
        "country_en": "Hungary",
        "city_en": "Budapest"
    },
    "96": {
        "id": 9678,
        "box": 0,
        "answer": 45,
        "name_hu": "Big Ben",
        "country_hu": "Egyesült Királyság",
        "city_hu": "London",
        "name_en": "Big Ben",
        "country_en": "United Kingdom",
        "city_en": "London"
    },
    "97": {
        "id": 9788,
        "box": 1910,
        "answer": 21,
        "name_hu": "Capitolium",
        "country_hu": "Egyesült Államok",
        "city_hu": "Washington",
        "name_en": "United States Capitol",
        "country_en": "United States of America",
        "city_en": "Washington"
    },
    "98": {
        "id": 9851,
        "box": 1218,
        "answer": 28,
        "name_hu": "Dohány utcai zsinagóga",
        "country_hu": "Magyarország",
        "city_hu": "Budapest",
        "name_en": "Dohány Street Synagogue",
        "country_en": "Hungary",
        "city_en": "Budapest"
    },
    "99": {
        "id": 9974,
        "box": 1724,
        "answer": 16,
        "name_hu": "Empire State Building",
        "country_hu": "Egyesült Államok",
        "city_hu": "New York",
        "name_en": "Empire State Building",
        "country_en": "United States of America",
        "city_en": "New York"
    }
};
