name: Deploy to GitHub Pages
permissions:
  contents: write

on:
  push:
    branches:
      - main   # or 'master', depending on your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./SearchWebpage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./SearchWebpage/dist  # or build, depending on your tool
